# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Osmandi's blog
  #email: hi@osmandi.com
description: >- # this means to ignore newlines until "baseurl:"
  Data Engineer & Chemical Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://osmandi.com" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb

# Build settings
# theme: hacked-jekyll
theme: minima
plugins:
  - jekyll-feed

# Customize theme hacked-jekyll
# lowercase: false
# newtab: true

# Theme personalization
minima:
  skin: dark
  social_links:
    - title: Portfolio
      icon: github
      url: "https://github.com/osmandi/portfolio"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/osmandi/"

author:
  name: Osmandi
  email: ""

# Edit permalinks to bogs
collections:
  posts:
    output: true
    permalink: /blog/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
