project:
  type: website
  output-dir: ./docs

website:
  title: "Osmandi's blog"
  favicon: ./profile.jpg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/osmandi
      - icon: linkedin
        href: https://linkedin.com/in/osmandi
  draft-mode: unlinked
format:
  html:
    toc: true
    code-fold: false
    number-sections: true
    toc-title: Contents
    theme:
      dark: darkly
      light: flatly
    css: styles.css

